services:
  postgres:
    user: postgres
    container_name: postgres
    shm_size: 128mb
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=aaa
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - ./postgres/pgdata:/var/lib/postgresql/data
      - ./postgres/create_tables.sql:/app/create_tables.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
