const defaultCategories = {
    Ubrania: [
        { name: 'T-shirty', rule: (nights) => nights + 1 },
        { name: 'Spodnie', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Bielizna', rule: (nights) => nights + 1 },
        { name: 'Skarpetki', rule: (nights) => nights + 1 },
        { name: 'Kurtka', rule: () => 1},
        { name: 'Buty', rule: (nights) => nights > 3 ? 2 : 1  },
    ],
    Kosmetyki: [
        { name: 'Szczoteczka do zębów', rule: () => 1 },
        { name: 'Szampon', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Żel pod prysznic', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Pasta do zębów', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Krem z filtrem UV', rule: () => 1 },
        { name: 'Dezodorant', rule: () => 1 },
        { name: 'Krem do rąk', rule: () => 1 },
        { name: 'Chusteczki higieniczne', rule: () => 1 },
    ],
    Elektronika: [
        { name: 'Ładowarka do telefonu', rule: () => 1 },
        { name: 'Powerbank', rule: () => 1 },
        { name: 'Adapter do gniazdka', rule: (nights) => 1 },
        { name: 'Słuchawki', rule: () => 1 },
    ],
    Plaża: [
        { name: 'Strój kąpielowy', rule: (nights) => Math.min(2, nights) },
        { name: 'Ręcznik', rule: (nights) => Math.ceil(nights / 7) },
        { name: 'Klapki', rule: () => 1 },
        { name: 'Okulary przeciwsłoneczne', rule: () => 1 },
        { name: 'Parasol plażowy', rule: () => 1 },
    ],
    Dziecko: [
        { name: 'Pieluchy', rule: (nights) => nights * 9 },
        { name: 'Mleko modyfikowane', rule: (nights) => Math.ceil(nights / 7) },
        { name: 'Zabawki', rule: () => 2 },
        { name: 'Ubrania zapasowe', rule: (nights) => nights + 2 },
        { name: 'Chusteczki nawilżane', rule: () => 1 },
        { name: 'Kocyk', rule: () => 1 },
    ],
    Apteczka: [
        { name: 'Leki podstawowe', rule: () => 1 },
        { name: 'Plastry', rule: () => 1 },
        { name: 'Środek na komary', rule: (nights) => nights > 2 ? 1 : 0 },
        { name: 'Termometr', rule: () => 1 },
        { name: 'Tabletki na ból głowy', rule: () => 1 },
        { name: 'Spray do nosa', rule: () => 1 },
    ],
    Dokumenty: [
        { name: 'Paszport/dowód', rule: () => 1 },
        { name: 'Bilety', rule: () => 1 },
        { name: 'Polisa ubezpieczeniowa', rule: () => 1 },
        { name: 'Rezerwacje hotelowe', rule: () => 1 },
        { name: 'Karta kredytowa', rule: () => 1 },
    ],
    Jedzenie: [
        { name: 'Przekąski', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Woda butelkowana', rule: (nights) => Math.ceil(nights / 1) },
    ],
    Sport: [
        { name: 'Buty sportowe', rule: () => 1 },
        { name: 'Strój sportowy', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Bidon na wodę', rule: () => 1 },
        { name: 'Ręcznik sportowy', rule: () => 1 },
        { name: 'Gumy oporowe', rule: () => 1 },
    ],
    Zima: [
        { name: 'Ciepła kurtka', rule: () => 1 },
        { name: 'Rękawiczki zimowe', rule: () => 1 },
        { name: 'Czapka zimowa', rule: () => 1 },
        { name: 'Buty zimowe', rule: () => 1 },
        { name: 'Termobielizna', rule: (nights) => Math.ceil(nights / 2) },
    ],
    Kemping: [
        { name: 'Namiot', rule: () => 1 },
        { name: 'Śpiwór', rule: () => 1 },
        { name: 'Karimata', rule: () => 1 },
        { name: 'Latarka', rule: () => 1 },
        { name: 'Zapałki/zapalniczka', rule: () => 1 },
        { name: 'Kuchenka turystyczna', rule: () => 1 },
        { name: 'Kawa/herbata', rule: () => 1 },
        { name: 'Sztućce', rule: () => 1 },
        { name: 'Kubek', rule: () => 1 },
        { name: 'Scyzoryk', rule: () => 1 },
        { name: 'Papier toaletowy', rule: (nights) => Math.ceil(nights / 5) },
    ],
    Biznes: [
        { name: 'Teczka na dokumenty', rule: () => 1 },
        { name: 'Telefon służbowy', rule: () => 1 },
        { name: 'Laptop', rule: () => 1 },
        { name: 'Notatnik', rule: () => 1 },
        { name: 'Długopis', rule: () => 1 },
    ],
    Eleganckie: [
        { name: 'Marynarka', rule: () => 1 },
        { name: 'Koszula', rule: (nights) => nights },
        { name: 'Spodnie garniturowe', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Krawat', rule: () => 1 },
        { name: 'Elegancka sukienka', rule: () => 1 },
        { name: 'Buty na obcasie', rule: () => 1 },
        { name: 'Torebka', rule: () => 1 },
        { name: 'Perfumy', rule: () => 1 },
        { name: 'Biżuteria', rule: () => 1 },
    ],
    Nocleg: [
        { name: 'Piżama', rule: () => 1 },
        { name: 'Poduszka podróżna', rule: () => 1 },
        { name: 'Zatyczki do uszu', rule: () => 1 },
        { name: 'Opaska na oczy', rule: () => 1 },
        { name: 'Prześcieradło', rule: () => 1 },
        { name: 'Mały ręcznik do twarzy', rule: () => 1 },
    ],

    Transport: [
        { name: 'Bilet lotniczy/kolejowy', rule: () => 1 },
        { name: 'Karta pokładowa', rule: () => 1 },
        { name: 'Poduszka podróżna', rule: () => 1 },
        { name: 'Maseczka ochronna', rule: () => 1 },
        { name: 'Żel antybakteryjny', rule: () => 1 },
        { name: 'Przekąski na drogę', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Butelka na wodę', rule: () => 1 },
    ],

    Rozrywka: [
        { name: 'Książka/Kindle', rule: () => 1 },
        { name: 'Karty do gry', rule: () => 1 },
        { name: 'Krzyżówki/łamigłówki', rule: () => 1 },
        { name: 'Słuchawki', rule: () => 1 },
        { name: 'Tablet', rule: () => 1 },
        { name: 'Ładowarka do tabletu', rule: () => 1 },
    ],
    Zwierzęta: [
        { name: 'Karma dla psa', rule: (nights) => nights * 2 },
        { name: 'Karma dla kota', rule: (nights) => nights * 2 },
        { name: 'Miski na wodę i jedzenie', rule: () => 1 },
        { name: 'Smycz', rule: () => 1 },
        { name: 'Zabawki dla zwierząt', rule: () => 2 },
        { name: 'Legowisko', rule: () => 1 },
        { name: 'Szczotka do sierści', rule: () => 1 },
    ],
}

module.exports = defaultCategories;
