const defaultCategories = {
    Clothes: [
        { name: 'T-shirts', rule: (nights) => nights + 1 },
        { name: 'Trousers', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Shorts', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Underwear', rule: (nights) => nights + 1 },
        { name: 'Socks', rule: (nights) => nights + 1 },
        { name: 'Jacket', rule: () => 1 },
        { name: 'Sweater/fleece', rule: () => 1 },
        { name: 'Raincoat/poncho', rule: () => 1 },
        { name: 'Belt', rule: () => 1 },
        { name: 'Hat/cap', rule: () => 1 },
        { name: 'Shoes', rule: (nights) => nights > 3 ? 2 : 1 },
        { name: 'Swimsuit', rule: () => 1 },
    ],
    Toiletries: [
        { name: 'Toothbrush', rule: () => 1 },
        { name: 'Shampoo', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Shower gel', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Toothpaste', rule: (nights) => Math.ceil(nights / 30) },
        { name: 'Sunscreen', rule: () => 1 },
        { name: 'Deodorant', rule: () => 1 },
        { name: 'Hand cream', rule: () => 1 },
        { name: 'Tissues', rule: () => 1 },
        { name: 'Razor/shaver', rule: () => 1 },
        { name: 'Hairbrush/comb', rule: () => 1 },
        { name: 'Lip balm', rule: () => 1 },
        { name: 'Cotton buds', rule: () => 1 },
        { name: 'Nail clippers', rule: () => 1 },
        { name: 'Makeup', rule: () => 1 },
        { name: 'Contact lenses & solution', rule: () => 1 },
    ],
    Electronics: [
        { name: 'Phone charger', rule: () => 1 },
        { name: 'Power bank', rule: () => 1 },
        { name: 'Socket adapter', rule: (nights) => 1 },
        { name: 'Headphones', rule: () => 1 },
    ],
    Beach: [
        { name: 'Swimsuit', rule: (nights) => Math.min(2, nights) },
        { name: 'Towel', rule: (nights) => Math.ceil(nights / 7) },
        { name: 'Flip-flops', rule: () => 1 },
        { name: 'Sunglasses', rule: () => 1 },
        { name: 'Beach umbrella', rule: () => 1 },
    ],
    Child: [
        { name: 'Diapers', rule: (nights) => nights * 9 },
        { name: 'Infant formula', rule: (nights) => Math.ceil(nights / 7) },
        { name: 'Baby bottle', rule: () => 2 },
        { name: 'Pacifier', rule: () => 2 },
        { name: 'Baby food', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Toys', rule: () => 2 },
        { name: 'Spare clothes', rule: (nights) => nights + 2 },
        { name: 'Wet wipes', rule: () => 1 },
        { name: 'Blanket', rule: () => 1 },
        { name: 'Stroller', rule: () => 1 },
        { name: 'Car seat', rule: () => 1 },
    ],
     FirstAid: [
        { name: 'Basic medicines', rule: () => 1 },
        { name: 'Plasters', rule: () => 1 },
        { name: 'Mosquito repellent', rule: (nights) => nights > 2 ? 1 : 0 },
        { name: 'Thermometer', rule: () => 1 },
        { name: 'Headache pills', rule: () => 1 },
        { name: 'Nasal spray', rule: () => 1 },
        { name: 'Bandages', rule: () => 1 },
        { name: 'Antiseptic wipes', rule: () => 1 },
        { name: 'Allergy medication', rule: () => 1 },
        { name: 'Prescription medicines', rule: () => 1 },
        { name: 'Sunburn cream', rule: () => 1 },
    ],
    Documents: [
        { name: 'Passport/ID', rule: () => 1 },
        { name: 'Tickets', rule: () => 1 },
        { name: 'Visa', rule: () => 1 },
        { name: 'Driving license', rule: () => 1 },
        { name: 'Insurance policy', rule: () => 1 },
        { name: 'Hotel reservations', rule: () => 1 },
        { name: 'Credit card', rule: () => 1 },
        { name: 'Emergency contacts', rule: () => 1 },
        { name: 'Copies of documents', rule: () => 1 },
    ],
    Food: [
        { name: 'Snacks', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Bottled water', rule: (nights) => Math.ceil(nights / 1) },
        { name: 'Instant soup', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Sandwiches', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Fruit', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Energy bars', rule: (nights) => nights },
        { name: 'Tea/coffee', rule: () => 1 },
        { name: 'Juice boxes', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Canned food', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Cutlery', rule: () => 1 },
        { name: 'Reusable food container', rule: () => 1 },
        { name: 'Napkins', rule: () => 1 },
        { name: 'Chewing gum', rule: () => 1 },
        { name: 'Special dietary foods', rule: () => 1 },
        { name: 'Thermos', rule: () => 1 },
    ],
    Sports: [
        { name: 'Sports shoes', rule: () => 1 },
        { name: 'Sportswear', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Water bottle', rule: () => 1 },
        { name: 'Sports towel', rule: () => 1 },
        { name: 'Resistance bands', rule: () => 1 },
        { name: 'Sports equipment', rule: () => 1 },
        { name: 'Swim goggles', rule: () => 1 },
    ],
    Winter: [
        { name: 'Warm jacket', rule: () => 1 },
        { name: 'Winter gloves', rule: () => 1 },
        { name: 'Winter hat', rule: () => 1 },
        { name: 'Winter boots', rule: () => 1 },
        { name: 'Thermal underwear', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Scarf', rule: () => 1 },
        { name: 'Thermal socks', rule: () => 1 },
        { name: 'Hand warmers', rule: () => 1 },
    ],
    Camping: [
        { name: 'Tent', rule: () => 1 },
        { name: 'Sleeping bag', rule: () => 1 },
        { name: 'Sleeping mat', rule: () => 1 },
        { name: 'Flashlight', rule: () => 1 },
        { name: 'Matches/lighter', rule: () => 1 },
        { name: 'Camping stove', rule: () => 1 },
        { name: 'Coffee/tea', rule: () => 1 },
        { name: 'Cutlery', rule: () => 1 },
        { name: 'Mug', rule: () => 1 },
        { name: 'Penknife', rule: () => 1 },
        { name: 'Toilet paper', rule: (nights) => Math.ceil(nights / 5) },
        { name: 'Camping chair', rule: () => 1 },
        { name: 'Portable grill', rule: () => 1 },
        { name: 'Water filter', rule: () => 1 },
        { name: 'Trash bags', rule: () => 1 },
    ],
    Business: [
        { name: 'Document folder', rule: () => 1 },
        { name: 'Work phone', rule: () => 1 },
        { name: 'Laptop', rule: () => 1 },
        { name: 'Notebook', rule: () => 1 },
        { name: 'Pen', rule: () => 1 },
        { name: 'Business cards', rule: () => 1 },
        { name: 'Portable mouse', rule: () => 1 },
        { name: 'USB stick', rule: () => 1 },
    ],
    Elegant: [
        { name: 'Blazer', rule: () => 1 },
        { name: 'Shirt', rule: (nights) => nights },
        { name: 'Suit trousers', rule: (nights) => Math.ceil(nights / 3) },
        { name: 'Tie', rule: () => 1 },
        { name: 'Elegant dress', rule: () => 1 },
        { name: 'Heels', rule: () => 1 },
        { name: 'Handbag', rule: () => 1 },
        { name: 'Perfume', rule: () => 1 },
        { name: 'Jewelry', rule: () => 1 },
        { name: 'Cufflinks', rule: () => 1 },
        { name: 'Watch', rule: () => 1 },
        { name: 'Evening bag', rule: () => 1 },
    ],
    Accommodation: [
        { name: 'Pajamas', rule: () => 1 },
        { name: 'Travel pillow', rule: () => 1 },
        { name: 'Earplugs', rule: () => 1 },
        { name: 'Sleep mask', rule: () => 1 },
        { name: 'Sheet', rule: () => 1 },
        { name: 'Small face towel', rule: () => 1 },
        { name: 'Slippers', rule: () => 1 },
        { name: 'Laundry bag', rule: () => 1 },
    ],
    Transport: [
        { name: 'Plane/train ticket', rule: () => 1 },
        { name: 'Boarding pass', rule: () => 1 },
        { name: 'Travel pillow', rule: () => 1 },
        { name: 'Snacks for the road', rule: (nights) => Math.ceil(nights / 2) },
        { name: 'Water bottle', rule: () => 1 },
        { name: 'Travel games', rule: () => 1 },
        { name: 'Neck pillow', rule: () => 1 },
        { name: 'Luggage tag', rule: () => 1 },
    ],
    Entertainment: [
        { name: 'Book/Kindle', rule: () => 1 },
        { name: 'Playing cards', rule: () => 1 },
        { name: 'Crosswords/puzzles', rule: () => 1 },
        { name: 'Headphones', rule: () => 1 },
        { name: 'Tablet', rule: () => 1 },
        { name: 'Tablet charger', rule: () => 1 },
        { name: 'Board games', rule: () => 1 },
        { name: 'Journal/diary', rule: () => 1 },
    ],
    Pets: [
        { name: 'Dog food', rule: (nights) => nights * 2 },
        { name: 'Cat food', rule: (nights) => nights * 2 },
        { name: 'Water and food bowls', rule: () => 1 },
        { name: 'Leash', rule: () => 1 },
        { name: 'Pet toys', rule: () => 2 },
        { name: 'Pet bed', rule: () => 1 },
        { name: 'Brush', rule: () => 1 },
        { name: 'Pet passport', rule: () => 1 },
        { name: 'Litter (for cats)', rule: () => 1 },
        { name: 'Waste bags', rule: () => 1 },
    ],
}

module.exports = defaultCategories
